version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: studyrats-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: study_rats
    ports:
#      porta pc:container
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
#      Comunicação entre os containers
      - studyrats-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: studyrats-app
    ports:
      - "9090:9090"
#      Só inicia se o mysql estiver "saudável"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - studyrats-network

volumes:
#  Mantém o dados do mysql mesmo que o container seja excluid
  mysql_data:

networks:
  studyrats-network:
    driver: bridge



